### ISSUE TITLE
Error with Gutenberg block

### ISSUE THREAD

**Issue by keesiemeijer** [billerickson/BE-Subpages-Widget#20]
I was checking out your Gutenberg block, and it worked fine at first. But after a while I get the same error as described here: https://github.com/WordPress/gutenberg/issues/4043

```
TypeError
columnNumber: 24486
fileName: "http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2"
lineNumber: 1
message: "this.activateMode is not a function"
stack: "
_createModes/<@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:24486
arrayEach@webpack-internal:///41:537:11
forEach@webpack-internal:///41:9359:14
_createModes@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:24449
initialize@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:23855
initialize@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:25475
initialize@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:28347
e.View@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:17:14728
constructor@http://test.dev/wp-includes/js/wp-backbone.min.js?ver=4.9.2:1:2602
constructor@http://test.dev/wp-includes/js/media-views.min.js?ver=4.9.2:1:23290
n@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:17:22929
n@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:17:22929
n@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:17:22929
[20]/wp.media@http://test.dev/wp-includes/js/media-models.min.js?ver=4.9.2:1:666
t@http://test.dev/wp-content/plugins/gutenberg/blocks/build/index.js?ver=1516268334:6:71380
constructClassInstance@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:125:436
beginWork@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:134:25
d@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393
f@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214
g@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462
t@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3
x@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247
r@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:164:368
v@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:163:278
updateContainer@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:172:31
Hb/<@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:83:450
unbatchedUpdates@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:169:269
Hb@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:83:420
render@http://test.dev/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:191:247
c@http://test.dev/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516268334:11:54108
window._wpLoadGutenbergEditor<@http://test.dev/wp-admin/post-new.php:1653:11
then/</</<@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:28766
i@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:27444
add@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:27748
then/</<@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:28738
each@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:2879
then/<@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:28684
a.Deferred@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:9:9928
then@http://test.dev/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=4.9.2:2:28661
@http://test.dev/wp-admin/post-new.php:1652:257
@http://test.dev/wp-admin/post-new.php:1652:3"
```

* Browser: Firefox
* Wordpress: 4.9.2
* PHP: 7.0.3
* Active Plugins: Gutenberg (2.0.0) and BE Subpages Widget (branch gutenberg)

As I'm new to Gutenberg I have no clue what the error means or if my setup is causing this error. If I de-activate your block the error goes away.

**Comment by billerickson** [comment]
I noticed a similar error. With the BE Subpages Widget plugin active, the Image block doesn't work either. It didn't make any sense to me because I'm not doing anything with media.

I haven't been able to figure out what's causing it, but I think you found the right issue in Gutenberg's GH repo. I'm going to follow that to see if there's something I need to do or if this is a core bug.

**Comment by keesiemeijer** [comment]
I've just cleared my browser history and now it all works again. I will let you know if the error returns.

**Comment by billerickson** [comment]
What happens if you try to add an Image block to the post? I get the following:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/252h2t1u420J3b2G0Z1K/Screen%20Shot%202018-01-23%20at%2010.14.51%20AM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=afb82aad)

**Comment by keesiemeijer** [comment]
Yes, I now get the same block error as you. And when I de-activate the plugin the image block works as it should.

And before (deleting browser history) I got this 
![screen shot 2018-01-23 at 17 33 19](https://user-images.githubusercontent.com/1436618/35287898-b676fcce-0063-11e8-9a50-b8ae8cd17126.png)

**Comment by keesiemeijer** [comment]
I was getting the same error with a block for my own plugin and fixed it by installing the babel-plugin-lodash plugin as described in the original issue. https://github.com/WordPress/gutenberg/issues/4043#issuecomment-361001527

It also reduced the file size of the build considerably :)

(https://github.com/keesiemeijer/related-posts-by-taxonomy/commit/81c0b9ef7a1aadf001df68bc6be7c34ec6f17391)

**Comment by ruucm-working** [comment]
I've had same error log when I use the other plugin-based react. 

Strangely It does not appear in chrome secret mode or the other server.

**Comment by paulmil11** [comment]
I am getting the same error with Sumo

TypeError: this.activateMode is not a function
    at https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:24791
    at Gt (https://load.sumo.com/9.f659a6e972c5b7671867.js:9:5219)
    at Function.Zo (https://load.sumo.com/9.f659a6e972c5b7671867.js:9:40178)
    at N.d._createModes (https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:24751)
    at N.d.initialize (https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:24160)
    at N.d.initialize (https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:25798)
    at N.d.initialize (https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:28670)
    at N.d.b.View (https://strategyu.co/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,backbone,wp-api-request&ver=5.1:11:14137)
    at N.d.constructor (https://strategyu.co/wp-includes/js/wp-backbone.min.js?ver=5.1:1:2616)
    at N.d.constructor (https://strategyu.co/wp-includes/js/media-views.min.js?ver=5.1:1:23607)

Deactivating sumo fixed the problem.  Any idea if this is a Sumo issue or a gutenberg issue?

**Comment by schuettemarkus** [comment]
> Deactivating sumo fixed the problem. Any idea if this is a Sumo issue or a gutenberg issue?

@paulmil11 same issue here with the Sumo plugin.
